spring:
  main:
    allow-circular-references: true
  application:
    name: cinema
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/movie?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  web:
    resources:
      static-locations: file:D://uploadIagme//file
server:
  port: 8066
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mybatis:
  mapper-locations: classpath:mapper/*Dao.xml



